Homework 2
================
Wenxin Tian
2023-10-03

``` r
library(tidyverse)
library(readxl)
```

## Problem 1

**Importing and cleaning pol-months.csv dataset:**

``` r
month_names = c("Jan","Feb","Mar",
                "Apr","May","Jun",
                "Jul","Aug","Sep",
                "Oct","Nov","Dec")

pols_df = 
  read_csv("data/pols-month.csv") |>
  janitor::clean_names() |>
  separate(mon, into = c('year', 'month', 'day'), '-') |>  # separate into year, month, and day
  mutate(year = as.numeric(year)) |>
  mutate(month = as.numeric(month)) |> 
  mutate(month = month_names[month]) |>                    # changing month num to month name
  mutate(                                                  # adding president variable
    president = case_match(
      prez_gop,
      1 ~ 'gop',
      0 ~ 'dem'
    )) |> 
  relocate(president, .after = month) |>                   # relocating president variable  
  select(-c(prez_dem, prez_gop, day))                      # removing prez_dem, prez_gop, and day variables
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
pols_df
```

    ## # A tibble: 822 × 9
    ##     year month president gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem
    ##    <dbl> <chr> <chr>       <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>
    ##  1  1947 Jan   dem            23      51     253      23      45     198
    ##  2  1947 Feb   dem            23      51     253      23      45     198
    ##  3  1947 Mar   dem            23      51     253      23      45     198
    ##  4  1947 Apr   dem            23      51     253      23      45     198
    ##  5  1947 May   dem            23      51     253      23      45     198
    ##  6  1947 Jun   dem            23      51     253      23      45     198
    ##  7  1947 Jul   dem            23      51     253      23      45     198
    ##  8  1947 Aug   dem            23      51     253      23      45     198
    ##  9  1947 Sep   dem            23      51     253      23      45     198
    ## 10  1947 Oct   dem            23      51     253      23      45     198
    ## # ℹ 812 more rows

**Importing and cleaning snp.csv dataset:**

``` r
snp_df = 
  read_csv("data/snp.csv") |>
  janitor::clean_names() |>
  separate(date, into = c('month', 'day', 'year'), '/') |>
  mutate(
    month = as.numeric(month),
    month = month_names[month],
    year = as.numeric(year) + 2000
  ) |>
  select(-day) |>
  arrange(year, month) |>
  relocate(month) |>
  relocate(year)
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
snp_df
```

    ## # A tibble: 787 × 3
    ##     year month close
    ##    <dbl> <chr> <dbl>
    ##  1  2000 Apr   1452.
    ##  2  2000 Aug   1518.
    ##  3  2000 Dec   1320.
    ##  4  2000 Feb   1366.
    ##  5  2000 Jan   1394.
    ##  6  2000 Jul   1431.
    ##  7  2000 Jun   1455.
    ##  8  2000 Mar   1499.
    ##  9  2000 May   1421.
    ## 10  2000 Nov   1315.
    ## # ℹ 777 more rows

**Importing and cleaning unemployment.csv:**

``` r
unemployment_df =
  read_csv("data/unemployment.csv") |>
  pivot_longer(
    Jan:Dec,
    names_to = "month",
    values_to = "unemployment_rate"
  ) |>
  janitor::clean_names()
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
unemployment_df
```

    ## # A tibble: 816 × 3
    ##     year month unemployment_rate
    ##    <dbl> <chr>             <dbl>
    ##  1  1948 Jan                 3.4
    ##  2  1948 Feb                 3.8
    ##  3  1948 Mar                 4  
    ##  4  1948 Apr                 3.9
    ##  5  1948 May                 3.5
    ##  6  1948 Jun                 3.6
    ##  7  1948 Jul                 3.6
    ##  8  1948 Aug                 3.9
    ##  9  1948 Sep                 3.8
    ## 10  1948 Oct                 3.7
    ## # ℹ 806 more rows

**Merging the 3 datasets together:**

``` r
result =
  left_join(pols_df, snp_df) |>
  left_join(unemployment_df)
```

    ## Joining with `by = join_by(year, month)`
    ## Joining with `by = join_by(year, month)`

``` r
result
```

    ## # A tibble: 822 × 11
    ##     year month president gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem close
    ##    <dbl> <chr> <chr>       <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <dbl>
    ##  1  1947 Jan   dem            23      51     253      23      45     198    NA
    ##  2  1947 Feb   dem            23      51     253      23      45     198    NA
    ##  3  1947 Mar   dem            23      51     253      23      45     198    NA
    ##  4  1947 Apr   dem            23      51     253      23      45     198    NA
    ##  5  1947 May   dem            23      51     253      23      45     198    NA
    ##  6  1947 Jun   dem            23      51     253      23      45     198    NA
    ##  7  1947 Jul   dem            23      51     253      23      45     198    NA
    ##  8  1947 Aug   dem            23      51     253      23      45     198    NA
    ##  9  1947 Sep   dem            23      51     253      23      45     198    NA
    ## 10  1947 Oct   dem            23      51     253      23      45     198    NA
    ## # ℹ 812 more rows
    ## # ℹ 1 more variable: unemployment_rate <dbl>

## Problem 2

**Importing and cleaning the Mr. Trash Wheel dataset:**

``` r
mrtrashwheel_df =
  read_excel(
    "data/trashwheel.xlsx",
    sheet = 1,
    range = "A2:N586") |>
  janitor::clean_names() |>
  mutate(year = as.numeric(year))
```

**Calculating `homes_powered` variable based on note:**

- Homes Powered - Each ton of trash equates to on average 500 kilowatts
  of electricity. An average household will use 30 kilowatts per day.

``` r
mrtrashwheel_df =
  mutate(
    mrtrashwheel_df,
    homes_powered = weight_tons * 500 / 30
  )

mrtrashwheel_df
```

    ## # A tibble: 584 × 14
    ##    dumpster month  year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr> <dbl> <dttm>                    <dbl>              <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31                 18
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74                 13
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45                 15
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1                  15
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06                 18
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71                 13
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91                  8
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7                  16
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52                 14
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76                 18
    ## # ℹ 574 more rows
    ## # ℹ 8 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <dbl>, homes_powered <dbl>

**Same process for Professor Trash Wheel and Gwynnda:**

``` r
professor_df =
  read_excel(
    "data/trashwheel.xlsx",
    sheet = 2,
    range = "A2:M108") |>
  janitor::clean_names() |>
  mutate(homes_powered = weight_tons * 500 / 30)

professor_df
```

    ## # A tibble: 106 × 13
    ##    dumpster month     year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr>    <dbl> <dttm>                    <dbl>              <dbl>
    ##  1        1 January   2017 2017-01-02 00:00:00        1.79                 15
    ##  2        2 January   2017 2017-01-30 00:00:00        1.58                 15
    ##  3        3 February  2017 2017-02-26 00:00:00        2.32                 18
    ##  4        4 February  2017 2017-02-26 00:00:00        3.72                 15
    ##  5        5 February  2017 2017-02-28 00:00:00        1.45                 15
    ##  6        6 March     2017 2017-03-30 00:00:00        1.71                 15
    ##  7        7 April     2017 2017-04-01 00:00:00        1.82                 15
    ##  8        8 April     2017 2017-04-20 00:00:00        2.37                 15
    ##  9        9 May       2017 2017-05-10 00:00:00        2.64                 15
    ## 10       10 May       2017 2017-05-26 00:00:00        2.78                 15
    ## # ℹ 96 more rows
    ## # ℹ 7 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, homes_powered <dbl>

``` r
gwynnda_df =
  read_excel(
    "data/trashwheel.xlsx",
    sheet = 4,
    range = "A2:L157") |>
  janitor::clean_names() |>
  mutate(homes_powered = weight_tons * 500 / 30)

gwynnda_df
```

    ## # A tibble: 155 × 12
    ##    dumpster month   year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr>  <dbl> <dttm>                    <dbl>              <dbl>
    ##  1        1 July    2021 2021-07-03 00:00:00        0.93                 15
    ##  2        2 July    2021 2021-07-07 00:00:00        2.26                 15
    ##  3        3 July    2021 2021-07-07 00:00:00        1.62                 15
    ##  4        4 July    2021 2021-07-16 00:00:00        1.76                 15
    ##  5        5 July    2021 2021-07-30 00:00:00        1.53                 15
    ##  6        6 August  2021 2021-08-11 00:00:00        2.06                 15
    ##  7        7 August  2021 2021-08-14 00:00:00        1.9                  15
    ##  8        8 August  2021 2021-08-16 00:00:00        2.16                 15
    ##  9        9 August  2021 2021-08-16 00:00:00        2.6                  15
    ## 10       10 August  2021 2021-08-17 00:00:00        3.21                 15
    ## # ℹ 145 more rows
    ## # ℹ 6 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, plastic_bags <dbl>, wrappers <dbl>,
    ## #   homes_powered <dbl>

**Combining 3 datasets:**

``` r
mrtrashwheel_df =
  mutate(
    mrtrashwheel_df,
    trashwheel = "mr_trashwheel"
  ) |>
  relocate(trashwheel)

professor_df =
  mutate(
    professor_df,
    trashwheel = "professor_trashwheel"
  ) |>
  relocate(trashwheel)

gwynnda_df =
  mutate(
    gwynnda_df,
    trashwheel = "gwynnda"
  ) |>
  relocate(trashwheel)

trashwheels_df = 
  bind_rows(mrtrashwheel_df, professor_df, gwynnda_df)

trashwheels_df
```

    ## # A tibble: 845 × 15
    ##    trashwheel    dumpster month  year date                weight_tons
    ##    <chr>            <dbl> <chr> <dbl> <dttm>                    <dbl>
    ##  1 mr_trashwheel        1 May    2014 2014-05-16 00:00:00        4.31
    ##  2 mr_trashwheel        2 May    2014 2014-05-16 00:00:00        2.74
    ##  3 mr_trashwheel        3 May    2014 2014-05-16 00:00:00        3.45
    ##  4 mr_trashwheel        4 May    2014 2014-05-17 00:00:00        3.1 
    ##  5 mr_trashwheel        5 May    2014 2014-05-17 00:00:00        4.06
    ##  6 mr_trashwheel        6 May    2014 2014-05-20 00:00:00        2.71
    ##  7 mr_trashwheel        7 May    2014 2014-05-21 00:00:00        1.91
    ##  8 mr_trashwheel        8 May    2014 2014-05-28 00:00:00        3.7 
    ##  9 mr_trashwheel        9 June   2014 2014-06-05 00:00:00        2.52
    ## 10 mr_trashwheel       10 June   2014 2014-06-11 00:00:00        3.76
    ## # ℹ 835 more rows
    ## # ℹ 9 more variables: volume_cubic_yards <dbl>, plastic_bottles <dbl>,
    ## #   polystyrene <dbl>, cigarette_butts <dbl>, glass_bottles <dbl>,
    ## #   plastic_bags <dbl>, wrappers <dbl>, sports_balls <dbl>, homes_powered <dbl>

**Dataset Description:**

In total, Mr. Trash Wheel, Professor Trash Wheel, and Gwynnda collected
845 dumpsters of trash, each contributing 584, 106, and 155 dumpsters,
respectively. The dataset includes basic information of trash collected
such as dumpster number, date, weight, and volume, as well as more
detailed information regarding the composition of trash being collected
like number of plastic bottles, cigarette butts, etc. Professor Trash
Wheel collected a total of 216.26 tons of trash. In July of 2021,
Gwynnda collected a total of 16300 cigarette butts.

## Problem 3

**Import baseline demographics dataset:**

``` r
baseline_df =
  read_csv("data/MCI_baseline.csv", skip = 1) |>
  janitor::clean_names() |>
  mutate(
    sex = case_match(
      sex,
      1 ~ "male",
      0 ~ "female"
    ),
    apoe4 = case_match(
      apoe4,
      1 ~ "carrier",
      0 ~ "non-carrier"
    )
  ) |>
  filter(current_age < age_at_onset | age_at_onset == ".")
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): Age at onset
    ## dbl (5): ID, Current Age, Sex, Education, apoe4
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
baseline_df
```

    ## # A tibble: 479 × 6
    ##       id current_age sex    education apoe4       age_at_onset
    ##    <dbl>       <dbl> <chr>      <dbl> <chr>       <chr>       
    ##  1     1        63.1 female        16 carrier     .           
    ##  2     2        65.6 female        20 carrier     .           
    ##  3     3        62.5 male          16 carrier     66.8        
    ##  4     4        69.8 female        16 non-carrier .           
    ##  5     5        66   male          16 non-carrier 68.7        
    ##  6     6        62.5 male          16 non-carrier .           
    ##  7     7        66.5 male          18 non-carrier 74          
    ##  8     8        67.2 female        18 non-carrier .           
    ##  9     9        66.7 female        16 non-carrier .           
    ## 10    10        64.1 female        18 non-carrier .           
    ## # ℹ 469 more rows

``` r
developed_mci = nrow(filter(baseline_df, age_at_onset != "."))

mean_age = mean(pull(baseline_df, current_age))

female_count = nrow(filter(baseline_df, sex == "female"))

male_count = nrow(filter(baseline_df, sex == "male"))

female_carrier_proportion = 
  nrow(filter(baseline_df, sex == "female" & apoe4 == "carrier")) / female_count * 100

baseline_df
```

    ## # A tibble: 479 × 6
    ##       id current_age sex    education apoe4       age_at_onset
    ##    <dbl>       <dbl> <chr>      <dbl> <chr>       <chr>       
    ##  1     1        63.1 female        16 carrier     .           
    ##  2     2        65.6 female        20 carrier     .           
    ##  3     3        62.5 male          16 carrier     66.8        
    ##  4     4        69.8 female        16 non-carrier .           
    ##  5     5        66   male          16 non-carrier 68.7        
    ##  6     6        62.5 male          16 non-carrier .           
    ##  7     7        66.5 male          18 non-carrier 74          
    ##  8     8        67.2 female        18 non-carrier .           
    ##  9     9        66.7 female        16 non-carrier .           
    ## 10    10        64.1 female        18 non-carrier .           
    ## # ℹ 469 more rows

**Dataset description:**

After importing the file, sex and carrier variables were converted from
numeric to descriptive for clarity. 4 participants who developed MCI
onset before the study were removed. Out of the remaining 479
participants, 210 were female, and 269 were male. The average baseline
age is 65.0286013. In total, 93 participants developed MCI during the
followup period. Out of the 210 female participants, 30% were APOE4
carriers.

**Import Amyloid biomarker dataset:**

``` r
amyloid_df =
  read_csv(
    "data/mci_amyloid.csv", 
    skip = 1,
    na = c("Na", "NA")) |>
  janitor::clean_names()
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): Study ID, Baseline, Time 2, Time 4, Time 6, Time 8
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
colnames(amyloid_df)[1] = "id"

amyloid_df
```

    ## # A tibble: 487 × 6
    ##       id baseline time_2 time_4 time_6 time_8
    ##    <dbl>    <dbl>  <dbl>  <dbl>  <dbl>  <dbl>
    ##  1     1    0.111 NA      0.109  0.105  0.107
    ##  2     2    0.107  0.109  0.109  0.106  0.107
    ##  3     3    0.106  0.109  0.106 NA      0.106
    ##  4     4    0.109  0.109  0.111  0.107  0.111
    ##  5     5    0.108  0.112  0.115  0.107  0.106
    ##  6     6    0.112  0.113  0.111  0.110  0.115
    ##  7     7    0.112 NA      0.104  0.112  0.112
    ##  8     8    0.110  0.109 NA      0.109  0.110
    ##  9     9    0.112  0.110  0.109 NA     NA    
    ## 10    10    0.112  0.112 NA     NA      0.110
    ## # ℹ 477 more rows

``` r
nrow(amyloid_df) - nrow(drop_na(amyloid_df))
```

    ## [1] 147

**Dataset description:**

After importing the data, the first column was changed from “study_id”
to “id” for consistency with `baseline_df`. Also, there were both “NA”s
and “Na”s in the dataset, so it had to be specified while reading in the
csv file. The dataset shows APOE4 values at the baseline and 4
timepoints after that with 2-year increments. It contains data of 487
participants, 147 of which are missing one or more APOE4 values. I
decided not to drop entries with missing values, as they still contain
valuable information.

**Check whether some participants appear in only the baseline or amyloid
datasets:**

``` r
baseline_only =  nrow(baseline_df) - nrow(filter(baseline_df, id %in% pull(amyloid_df, id)))

amyloid_only = nrow(amyloid_df) - nrow(filter(amyloid_df, id %in% pull(baseline_df, id)))
```

8 participants were only found in the baseline dataset, whereas 16
participants were only found in the amyloid dataset.

**Combining demographic and biomarker datasets:**

``` r
baseline_amyloid_df =
  merge(baseline_df, amyloid_df, by = "id")

write_csv(baseline_amyloid_df, "data/baseline_amyloid.csv")
```

**Dataset description:**

The combined dataset contains information of 471 participants who appear
in both baseline and amyloid datasets, including basic demographic
information and APOE4 values across 5 different timepoints. The
resulting dataset is exported to `baseline_amyloid.csv` under the `data`
directory.
