---
title: "Homework 2"
author: "Wenxin Tian"
date: "`r Sys.Date()`"
output: github_document
---

```{r, message=FALSE}
library(tidyverse)
```

## Problem 1

Importing and cleaning pol-months.csv dataset:

```{r}
month_names = c("Jan","Feb","Mar",
                "Apr","May","Jun",
                "Jul","Aug","Sep",
                "Oct","Nov","Dec")

pols_df = 
  read_csv("data/pols-month.csv") |>
  janitor::clean_names() |>
  separate(mon, into = c('year', 'month', 'day'), '-') |>  # separate into year, month, and day
  mutate(year = as.numeric(year)) |>
  mutate(month = as.numeric(month)) |> 
  mutate(month = month_names[month]) |>                    # changing month num to month name
  mutate(                                                  # adding president variable
    president = case_match(
      prez_gop,
      1 ~ 'gop',
      0 ~ 'dem'
    )) |> 
  relocate(president, .after = month) |>                   # relocating president variable  
  select(-c(prez_dem, prez_gop, day))                      # removing prez_dem, prez_gop, and day variables

pols_df
```

Importing and cleaning snp.csv dataset:

```{r}
snp_df = 
  read_csv("data/snp.csv") |>
  janitor::clean_names() |>
  separate(date, into = c('month', 'day', 'year'), '/') |>
  mutate(
    month = as.numeric(month),
    month = month_names[month],
    year = as.numeric(year) + 2000
  ) |>
  select(-day) |>
  arrange(year, month) |>
  relocate(month) |>
  relocate(year)

snp_df
```

Importing and cleaning unemployment.csv:

```{r}
unemployment_df =
  read_csv("data/unemployment.csv") |>
  pivot_longer(
    Jan:Dec,
    names_to = "month",
    values_to = "unemployment_rate"
  ) |>
  janitor::clean_names()

unemployment_df
```

Merging the 3 datasets together:

```{r}
result =
  left_join(pols_df, snp_df) |>
  left_join(unemployment_df)

result
```

